# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20160727_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='links',
            new_name='likes',
        ),
    ]
